<a href="https://colab.research.google.com/github/akshatsingh523/AIML-projects/blob/main/open_ai_clip_object_detection_model_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install git+https://github.com/PrithivirajDamodaran/ZSIC.git

  Cloning https://github.com/PrithivirajDamodaran/ZSIC.git to /tmp/pip-req-build-8vxbrnat
  Running command git clone --filter=blob:none --quiet https://github.com/PrithivirajDamodaran/ZSIC.git /tmp/pip-req-build-8vxbrnat
  Resolved https://github.com/PrithivirajDamodaran/ZSIC.git to commit dbd1a8b7db5a7ec7fcab168e818681aa11fd95ca
  Preparing metadata (setup.py) ... done
  Created wheel for ZSIC: filename=ZSIC-1.0-py3-none-any.whl size=4797 sha256=81613e205f4d96f7c2636d0defabf72113eb62f5c9d93de701f1ba90bb4e50e5
  Stored in directory: /tmp/pip-ephem-wheel-cache-dewn99le/wheels/fe/07/71/0ba6ffc0d57206230fbaeeb8261f17d205bf0ba159fc1e167e
Successfully built ZSIC


In [ ]:
from ZSIC import ZeroShotImageClassification

In [ ]:
zsic = ZeroShotImageClassification()

Loading OpenAI CLIP model ViT-B/32 ...


100%|████████████████████████████████████████| 338M/338M [00:02<00:00, 137MiB/s]


Label language en ...


In [ ]:
from PIL import Image
import requests

In [ ]:
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

In [ ]:
#Predictions
preds = zsic(image=image,
            candidate_labels=["birds", "lions", "cats","dogs"],
            )
print(preds)
print(preds['labels'][preds['scores'].index(max(preds['scores']))])

{'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=640x480 at 0x795596453CA0>, 'scores': (0.9940925, 0.0028710056, 0.0025102566, 0.00052617834), 'labels': ('cats', 'lions', 'dogs', 'birds')}
cats


In [ ]:
!pip install transformers

In [ ]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-large-patch14")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-large-patch14")




(…)t-large-patch14/resolve/main/config.json:   0%|          | 0.00/4.52k [00:00<?, ?B/s]

`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.


model.safetensors:   0%|          | 0.00/1.71G [00:00<?, ?B/s]

(…)14/resolve/main/preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

(…)tch14/resolve/main/tokenizer_config.json:   0%|          | 0.00/905 [00:00<?, ?B/s]

(…)it-large-patch14/resolve/main/vocab.json:   0%|          | 0.00/961k [00:00<?, ?B/s]

(…)it-large-patch14/resolve/main/merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

(…)arge-patch14/resolve/main/tokenizer.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]

(…)h14/resolve/main/special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

In [ ]:
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

inputs = processor(text=["a photo of a cat", "a photo of a dog"], images=image, return_tensors="pt", padding=True)

outputs = model(**inputs)
logits_per_image = outputs.logits_per_image # this is the image-text similarity score
probs = logits_per_image.softmax(dim=1) # we can take the softmax to get the label probabilities

In [ ]:
probs

tensor([[9.9925e-01, 7.5487e-04]], grad_fn=<SoftmaxBackward0>)

In [ ]:
print(outputs.logits_per_image)

tensor([[18.9041, 11.7159]], grad_fn=<TBackward0>)


In [ ]:
import torch.nn.functional as nnf
prob = nnf.softmax(probs, dim=1)

top_p, top_class = probs.topk(1, dim = 1)

In [ ]:
top_class

tensor([[0]])

In [ ]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")




(…)it-base-patch32/resolve/main/config.json:   0%|          | 0.00/4.19k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/605M [00:00<?, ?B/s]

(…)32/resolve/main/preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

(…)tch32/resolve/main/tokenizer_config.json:   0%|          | 0.00/568 [00:00<?, ?B/s]

(…)vit-base-patch32/resolve/main/vocab.json:   0%|          | 0.00/862k [00:00<?, ?B/s]

(…)vit-base-patch32/resolve/main/merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

(…)base-patch32/resolve/main/tokenizer.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]

(…)h32/resolve/main/special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

In [ ]:
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

inputs = processor(text=["a photo of a cat", "a photo of a dog"], images=image, return_tensors="pt", padding=True)

outputs = model(**inputs)
logits_per_image = outputs.logits_per_image # this is the image-text similarity score
probs = logits_per_image.softmax(dim=1) # we can take the softmax to get the label probabilities

In [ ]:
import torch.nn.functional as nnf
prob = nnf.softmax(probs, dim=1)

top_p, top_class = probs.topk(1, dim = 1)

In [ ]:
top_p

tensor([[0.9949]], grad_fn=<TopkBackward0>)

In [ ]:
from PIL import Image
import requests
from transformers import CLIPProcessor, CLIPModel
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch16")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch16")



(…)it-base-patch16/resolve/main/config.json:   0%|          | 0.00/4.10k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/599M [00:00<?, ?B/s]

(…)16/resolve/main/preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

(…)tch16/resolve/main/tokenizer_config.json:   0%|          | 0.00/905 [00:00<?, ?B/s]

(…)vit-base-patch16/resolve/main/vocab.json:   0%|          | 0.00/961k [00:00<?, ?B/s]

(…)vit-base-patch16/resolve/main/merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

(…)base-patch16/resolve/main/tokenizer.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]

(…)h16/resolve/main/special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

In [ ]:
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
inputs = processor(text=["a photo of a cat", "a photo of a dog"], images=image, return_tensors="pt", padding=True)
outputs = model(**inputs)
logits_per_image = outputs.logits_per_image # this is the image-text similarity score
probs = logits_per_image.softmax(dim=1) # we can take the softmax to get the label probabilities

In [ ]:
import torch.nn.functional as nnf
prob = nnf.softmax(probs, dim=1)

top_p, top_class = probs.topk(1, dim = 1)

In [ ]:
top_p

tensor([[0.9992]], grad_fn=<TopkBackward0>)

In [ ]:
top_class

tensor([[0]])